language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - if [ ${DOCKER_IMAGE} ]; then docker pull $DOCKER_IMAGE; fi
  - if [ -z ${DOCKER_IMAGE+x} ]; then python setup.py develop; fi

script:
  - if [ ${DOCKER_IMAGE} ]; docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh; fi
  - if [ ${DOCKER_IMAGE} ]; ls wheelhouse/; fi
  - if [ -z ${DOCKER_IMAGE+x} ]; then python setup.py test; fi
